# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /nuevoPrestamo
            logout:
                path: /logout
                target: /login
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMINISTRADOR }
    providers:
        usuarios:
            entity: { class: Acme\AdministradorBundle\Entity\Administrador, property: idadmin }
    encoders:
        Acme\AdministradorBundle\Entity\Administrador: { algorithm: sha512, encode_as_base64: false, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512